## This workflow runs on all pull requests and issues.
## It greets new contributors when they create their first issue or open their first pull request.
##
## More details on https://github.com/actions/first-interaction

name: Build Java app

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
    - name: Checkout
      uses: actions/checkout@v4.2.2
    - name: Setup Java JDK
      uses: actions/setup-java@v3.14.1
      with:
        # The Java version to set up. Takes a whole or semver Java version. See examples of supported syntax in README file
        java-version: 21
        distribution: temurin
    - name: Run mvn to build
      run: | 
        cd java-app
        mvn clean install
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v4.6.2
      with:
        # Artifact name
        name: javaapp
        # A file, directory or wildcard pattern that describes what to upload
        path: "./target/*.jar"
    
        
    
